name: Build and Release Android APK

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: 'Build APK'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'

      - name: Build Vue
        run: |
          npm i
          npm run build

      - name: Sync Capacitor
        run: |
          npx cap sync

      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.jks

      - name: Build app apk
        run: |
          chmod +x ./android/gradlew
          npx cap build --keystorepath release.jks --keystorepass ${{ secrets.RELEASE_KEYSTORE_PASSWORD }} --keystorealias release --keystorealiaspass ${{ secrets.RELEASE_KEYSTORE_PASSWORD }} --androidreleasetype APK android

      - name: Upload release apk
        uses: actions/upload-artifact@v3
        with:
          name: electr
          path: android/app/build/outputs/apk/release/app-release-signed.apk
          retention-days: 1

  release:
    name: 'Create Release'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: 'Download Artifact'
        uses: actions/download-artifact@v3
        with:
          name: electr

      - name: 'Rename Artifact'
        run: mv app-release-signed.apk electr${{ github.ref_name }}.apk

      - name: 'Create Release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: electr${{ github.ref_name }}.apk
          prerelease: true
          generateReleaseNotes: true
          tag: ${{ github.ref_name || '0.1.0' }}
