name: Android Build

on:
  push:
    branches:
    - main

jobs:
  build:
    name: 'Build APK'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Build Vue
        run: |
          npm i
          npm run build

      - name: Sync Capacitor
        run: |
          npx cap add android
          npx cap sync

      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.jks

      - name: Build app apk
        run: npx cap build --keystorepath release.jks --keystorepass ${{ secrets.RELEASE_KEYSTORE_PASSWORD }} --keystorealias release --keystorealiaspass ${{ secrets.RELEASE_KEYSTORE_PASSWORD }} --androidreleasetype APK android

      - name: Upload release apk
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release-signed.apk
          retention-days: 60
